---
apiVersion: v1
kind: Pod
metadata:
  name: app-livenessprob
  namespace: demoAI
spec:
  containers:
  - name: app
    image: gcr.io/durable-spot-386111/demo:v1.0.0
    
    ports:
    - containerPort: 8000
      name: http
    livenessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 20
      failureThreshold: 2
