---
apiVersion: v1
kind: Pod
metadata:
  name: app-readinessprobe
spec:
  containers:
  - name: app
    image: gcr.io/durable-spot-386111/demo:v1.0.0
   
    readinessProbe:
      httpGet:
        path: /ready
        port: 8888
      periodSeconds: 2
      initialDelaySeconds: 0
      failureThreshold: 3
      successThreshold: 1
   
    livenessProbe:
      httpGet:
        path: /
        port: 8888
      periodSeconds: 20
      initialDelaySeconds: 5
      timeoutSeconds: 2
      failureThreshold: 2
    
    ports:
      - containerPort: 8888
        name: http

