---
apiVersion: v1
kind: Pod
metadata:
  name: app-multi-containers
spec:
  containers:
  - name: container1
    image: nginx
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html
  
  - name: container2
    image: busybox
    volumeMounts:
    - name: shared-volume
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /shared-volume/index.html;
          sleep 2;
        done

  volumes:
  - name: shared-volume
    emptyDir: {}
