apiVersion: v1
kind: Pod
metadata:
  name: app-volume
spec:
  containers:
  - name: app
    image: gcr.io/kuar-demo/kuard-amd64:1
    volumeMounts:
    - name: "data"
      mountPath: "data"
  
  volumes:
  - name: "data"
    hostPath:
      path: "/var/lib/app"
