---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: demo
spec:
  containers:
  - name: app
    image: gcr.io/durable-spot-386111/demo:v1.0.0
    ports:
    - name: http
      containerPort: 8080
